# Generated by Django 5.2.9 on 2026-01-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='patient',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
