# Generated by Django 5.2.9 on 2026-01-05 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_managers_alter_patient_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='patient_images/'),
        ),
        migrations.AddField(
            model_name='patient',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
