# Generated by Django 5.2.9 on 2026-01-04 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesslog',
            options={'ordering': ('-accessed_at',)},
        ),
        migrations.RemoveField(
            model_name='accesslog',
            name='session_duration',
        ),
        migrations.AddField(
            model_name='accesslog',
            name='validation_status',
            field=models.CharField(choices=[('AUTHORIZED', 'Authorized'), ('BLACKLISTED', 'Blacklisted'), ('NOT_FOUND', 'Not Found'), ('PENDING', 'Pending Verification')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='access_type',
            field=models.CharField(choices=[('EMERGENCY', 'Emergency Access'), ('AUTHORIZED', 'Authorized Access'), ('ROUTINE', 'Routine Check')], default='EMERGENCY', max_length=20),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_access_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
