# Generated by Django 5.2.9 on 2026-01-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_alter_accesslog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='state_medical_council',
            field=models.CharField(default='Andhra Pradesh Medical Council', max_length=100),
        ),
    ]
