# Generated by Django 5.2.9 on 2026-01-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_doctor_state_medical_council'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='registration_number_used',
            field=models.CharField(blank=True, help_text='Registration number used for validation', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='state_council_used',
            field=models.CharField(blank=True, help_text='State medical council used for validation', max_length=100, null=True),
        ),
    ]
